#!/usr/bin/env node
// Builds audits/README.md: one row per audit, every number read from scan.json/meta.json.
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

export function rowFor(name, meta, findings) {
  const hooks = findings.filter((f) => f.kind === 'hook');
  const installers = findings.filter((f) => f.kind === 'installer');
  return {
    name,
    repo: meta.repo,
    commit: meta.commit.slice(0, 7),
    plugins: meta.plugins,
    hooks: hooks.length,
    inline: hooks.filter((h) => h.inlineCode).length,
    mcp: findings.filter((f) => f.kind === 'mcp').length,
    unpinned: findings.filter((f) => f.pinned === false).length,
    life: findings.filter((f) => f.kind === 'lifecycle').length,
    // An installer whose writes were not traced is not "no backup": it gets its
    // own column, or a confirmed overwrite (ECC) would show as 0 here.
    noBackup: installers.filter((f) => f.backup === false).length,
    untraced: installers.filter((f) => f.traced === false).length,
    // Otherwise a repo whose only finding is an installer with a backup reads as all zeros.
    backup: installers.filter((f) => f.backup === true).length,
    high: findings.filter((f) => f.level === 'high').length,
    total: findings.length,
  };
}

export function buildIndex(dir) {
  const rows = [];
  for (const name of readdirSync(dir, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)) {
    const m = join(dir, name, 'meta.json');
    const s = join(dir, name, 'scan.json');
    if (!existsSync(m) || !existsSync(s) || !existsSync(join(dir, name, 'audit.md'))) continue;
    rows.push(rowFor(name, JSON.parse(readFileSync(m, 'utf8')), JSON.parse(readFileSync(s, 'utf8')).findings));
  }
  rows.sort((a, b) => b.total - a.total || a.repo.localeCompare(b.repo));

  const nothing = rows.filter((r) => r.total === 0).length;
  const sum = (k) => rows.reduce((n, r) => n + r[k], 0);
  const L = [];
  L.push('# Audits — what runs without asking', '');
  // How many owners were notified is read from the audits themselves.
  const notified = rows.filter((r) => /The owner was notified on/.test(readFileSync(join(dir, r.name, 'audit.md'), 'utf8'))).length;
  L.push(
    notified
      ? `**Status:** snapshot at the commits shown. ${notified} of ${rows.length} owners were notified by an issue (linked in each audit); the others have not been contacted. Corrections are welcome as an issue.`
      : '**Status:** snapshot at the commits shown. Owners have not been contacted yet; corrections are welcome as an issue.',
    '',
  );
  L.push(`${rows.length} repos. ${nothing} declare nothing that runs on its own. Across all of them: ${sum('hooks')} hooks (${sum('inline')} with inline code), ${sum('mcp')} MCP servers, ${sum('unpinned')} hooks or servers that run a registry package without a pinned version, ${sum('life')} npm install-time scripts, ${sum('noBackup')} installer targets with no backup code and ${sum('untraced')} installers whose writes were not traced by the scanner (see each audit for the manual check), ${sum('high')} high-level findings.`, '');
  L.push('Counts are what is **declared**, not a judgement. A plugin whose purpose is to hook every tool will have many hooks. Read each audit.', '');
  L.push('| repo | commit | plugins | hooks (inline) | MCP | unpinned | npm install scripts | installer, backup found | installer, no backup | installer, not traced | high |');
  L.push('|---|---|---|---|---|---|---|---|---|---|---|');
  for (const r of rows) {
    L.push(`| [${r.repo}](${r.name}/audit.md) | ${r.commit} | ${r.plugins} | ${r.hooks} (${r.inline}) | ${r.mcp} | ${r.unpinned} | ${r.life} | ${r.backup} | ${r.noBackup} | ${r.untraced} | ${r.high} |`);
  }
  L.push('', 'Generated by `tools/audit-index.mjs` from each `scan.json`. Method: [`docs/AUDIT-METHOD.md`](../docs/AUDIT-METHOD.md).', '');
  return { text: L.join('\n'), rows, nothing };
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const dir = join(fileURLToPath(new URL('..', import.meta.url)), 'audits');
  const { text, rows, nothing } = buildIndex(dir);
  writeFileSync(join(dir, 'README.md'), text);
  console.log(`${rows.length} audits indexed; ${nothing} with nothing declared`);
}
